image: nexus3.int.rclabenv.com/ringcentral/web-tools:node20-openjdk17-alpine

default:
  tags:
    - ags-runner
    - deploy

stages:
  - test
  - deploy

variables:
  GITDOCS_URL: "$CI_PAGES_URL"
  NPM_CONFIG_REGISTRY: "https://nexus.int.rclabenv.com/nexus/content/groups/npm-all/"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm config set registry "$NPM_CONFIG_REGISTRY"
  - npm ci --cache .npm --prefer-offline

test:
  stage: test
  script:
    - npm test
    - npm run build

pages:
  stage: deploy
  script:
    - npm run build:pages
    - rm -rf public
    - cp -r dist public
  artifacts:
    paths:
      - public
  environment:
    name: gitdocs
    url: $GITDOCS_URL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
